# Generated by Django 4.1 on 2024-01-03 08:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("school", "0002_coursesmodule"),
    ]

    operations = [
        migrations.CreateModel(
            name="ScheduleModule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("poster", models.ImageField(upload_to="events")),
                ("category", models.CharField(max_length=20)),
                ("heading", models.CharField(max_length=35)),
                ("date", models.TextField()),
                ("duration", models.TextField()),
                ("price", models.IntegerField()),
            ],
        ),
    ]
