# Generated by Django 4.1 on 2024-01-03 08:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("school", "0005_alter_schedulemodule_isdone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="schedulemodule",
            name="isdone",
            field=models.BooleanField(default=False),
        ),
    ]
