# Generated by Django 4.1 on 2024-01-03 09:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("school", "0007_teamdeatilsmodule"),
    ]

    operations = [
        migrations.CreateModel(
            name="TestimonialModule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("isvisible", models.BooleanField()),
                ("selfie", models.ImageField(upload_to="testimonial")),
                ("description", models.TextField()),
                ("category", models.CharField(max_length=30)),
                ("name", models.CharField(max_length=30)),
            ],
        ),
    ]
